Repository FACETICKER/server, pull requests merged in 2023-08, with the labels that each got.

#69 방문자 스티커 위치 수정
  config/express.js
  config/swagger.js
  index.js
  package.json
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#70 사자성어 추가
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement

#71 response, 쿼리문 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: enhancement

#72 Update: 새로운 질문 조회
  src/app/user/userService.js
Labels: enhancement

#73 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#74 Fix: 스웨거 수정
  src/app/user/userRoute.js
Labels: enhancement

#75 Develop
  src/app/user/userRoute.js
Labels: enhancement

#77 Develop
  src/app/user/userRoute.js
Labels: enhancement

#78 Fix: 방문자 질문 등록 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#79 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#80 Fix: 카카오 로그인
  src/app/user/userController.js
Labels: enhancement

#81 Update: Error 내역 출력 + Fix: 방문자 플로우 질문 조회
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#82 Update: Error 내역 출력 + Fix: 방문자 플로우 질문 조회
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#85 Update: N문N답 호스트 플로우 조회 수정
  src/app/user/userController.js
Labels: enhancement

#86 Develop
  src/app/user/userController.js
Labels: enhancement

#88 Update: 로그인 라우트 수정
  src/app/user/userRoute.js
Labels: enhancement

#89 Develop
  src/app/user/userRoute.js
Labels: enhancement

#90 Fix: 오류 수정
  src/app/user/userRoute.js
Labels: enhancement

#91 Develop
  src/app/user/userRoute.js
Labels: enhancement

#103 포스터 정보 수정
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#108 Issue/104
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#114 N문 N답 API JWT 미들웨어 추가 + API 수정
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: enhancement

#119 Update: 스티커 위치 수정
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#120 Update: 호스트 메세지 등록 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#121 방문자 메세지 등록
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#123 방문자 스티커 닉네임 등록
  index.js
  package-lock.json
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#124 EB 에러 수정
  index.js
  src/app/user/userRoute.js
Labels: bug fix

#131 Fix: redirect_uri 수정
  src/app/user/userController.js
Labels: enhancement

#133 Update: 메인 페이지 조회 수정
  src/app/user/userDao.js
Labels: enhancement

#134 Update: 메인 페이지 조회 수정
  src/app/user/userService.js
Labels: enhancement

#135 Issue/29
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: enhancement

#136 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#138 Issue/137
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: enhancement

#139 Update: 코드 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#143 Update: EB HTTPS 설정 추가
  src/app/user/userRoute.js
Labels: enhancement

#144 Develop
  src/app/user/userRoute.js
Labels: enhancement

#145 Nginx 리버스 프록시 설정 수정
  .platform/nginx.conf
Labels: enhancement

#146 Nginx frontend 기본 라우팅 수정
  .platform/nginx.conf
Labels: enhancement

#148 삭제 API
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#150 Nginx 설정 파일 수정
  .platform/nginx/nginx.conf
Labels: enhancement

#151 삭제 API
  src/app/user/userRoute.js
Labels: enhancement

#155 수정 API를 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: enhancement

#156 Update: 수정 API
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: enhancement

#157 스티커 수정 API 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement

#158 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#160 Fix: N문 N답 조회
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: bug

#161 Issue/159
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: bug fix

#162 Develop
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: bug fix

#163 Fix: JWT 미들웨어
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: bug fix

#165 Update: 방문자 스티커 등록 수정
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement

#166 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#168 Update: sticker details 예외 처리
  src/app/user/userController.js
Labels: enhancement

#170 응답 형식 수정
  src/app/user/userService.js
Labels: enhancement

#171 Update: 구글 redirect uri
  src/app/user/userController.js
  src/app/user/userRoute.js
Labels: enhancement

#174 Develop
  src/app/user/userDao.js
Labels: enhancement

#175 Update: 방문자 스티커 닉네임 등록 API 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#176 Issue/164
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: enhancement

#177 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#180 Update: 스티커 부착 수정
  src/app/user/userController.js
Labels: enhancement

#181 Develop
  src/app/user/userController.js
  src/app/user/userRoute.js
Labels: enhancement

#183 EB 불필요한 환경변수 제거
  .platform/nginx/nginx.conf
Labels: bug fix

#184 Update: 방문자 스티커 전체 조회 수정
  src/app/user/userDao.js
Labels: enhancement

#185 Develop
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: enhancement

#188 Fix: 방문자 스티커 삭제
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
Labels: bug fix

#189 Fix: 방문자 스티커 삭제
  src/app/user/userRoute.js
Labels: bug fix

#190 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
Labels: bug fix

#191 Fix: 포스터 수정 스웨거
  .platform/nginx/nginx.conf
  src/app/user/userRoute.js
Labels: bug fix

#192 Develop
  src/app/user/userRoute.js
Labels: bug fix

#193 Update: 질문 등록 API
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#194 Develop
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#197 Update: 호스트 메세지 조회 수정
  src/app/user/userController.js
Labels: enhancement

#201 Update: 질문, 답변 생성 시간 + 예외처리
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
Labels: enhancement

#202 Develop
  config/baseResponse.js
  src/app/user/userController.js
  src/app/user/userDao.js
Labels: enhancement

#203 Update: 스티커 API 수정
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#204 Develop
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#206 Develop
  src/app/user/userController.js
Labels: enhancement

#207 Update: 포스터 정보 등록
  src/app/user/userController.js
Labels: enhancement

#212 Issue/211
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#213 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#214 Update: Seen API 수정
  src/app/user/userController.js
Labels: enhancement

#215 Update: Seen API 스웨거 수정
  src/app/user/userRoute.js
Labels: enhancement

#216 Update: 메인 페이지 조회 수정
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#217 Develop
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#218 Update: 소셜 로그인 redirect uri 수정
  src/app/user/userController.js
Labels: enhancement

#221 Issue/219
  package-lock.json
  package.json
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#222 Develop
  package-lock.json
  package.json
  src/app/user/userController.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#223 Update: 이미지 업로드
  src/app/user/userController.js
Labels: enhancement

#224 Develop
  src/app/user/userController.js
Labels: enhancement

#226 Update: roll back
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#227 Update: redirect uri 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#230 Issue/219
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement

#231 Develop
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement

#232 Update: redirect uri
  src/app/user/userController.js
Labels: enhancement

#233 Update: redirect uri
  src/app/user/userController.js
Labels: enhancement

#234 Update: parser limit 조절
  .platform/nginx/nginx.conf
  config/express.js
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#236 Develop
  .platform/nginx/nginx.conf
  config/express.js
  src/app/user/userController.js
  src/app/user/userService.js
Labels: enhancement

#237 Update: 새로운 스티커 조회 수정
  src/app/user/userDao.js
Labels: enhancement

#238 Update: redirect uri 수정
  src/app/user/userController.js
Labels: enhancement

#239 Update: 카카오 redirect uri 수정
  src/app/user/userController.js
Labels: enhancement

#246 Update: 스티커 개수 API 수정
  src/app/user/userDao.js
Labels: enhancement
